select * from customer limit 20

--Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue
from customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount) from customer)

--Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, AVG(review_rating)
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select round(avg(purchase_amount),2) as avg_purchase_amount, shipping_type
from customer
where shipping_type in ('Express','Standard')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select  subscription_status,count(customer_id) as total_customers,round(sum(purchase_amount),2) as amount_spent
from customer
group by subscription_status

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
ROUND(100*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_percentage
FROM customer
GROUP BY item_purchased
order by discount_percentage desc
limit 5

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
case
	when previous_purchases=1 then 'new'
	when previous_purchases between 2 and 10 then 'returning'
	else 'loyal'
	end as customer_segments
from customer
)
select customer_segments, count(*) as "Number_of_Customers"
from customer_type
group by customer_segments
order by "Number_of_Customers" desc

--Q8. What are the top 3 most purchased products within each category?
with item_count as (
select category, item_purchased, 
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc ) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_count
where item_rank<=3

--Q9. Are customers Who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as "repeat_buyers"
from customer
where previous_purchases>5
group by subscription_status

--Q10. What is the revenue contribution of each age group
select age_groups, sum(purchase_amount) as revenue_contribution
from customer
group by age_groups
order by sum(purchase_amount) desc